#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Working Copy from ra9b385bc*/

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void vrptimeout_deliver 
    (__po_hi_request_t* request);

void* vrptimeout_job (void);

void lrltimeout_deliver 
    (__po_hi_request_t* request);

void* lrltimeout_job (void);

void vvimode_deliver 
    (__po_hi_request_t* request);

void* vvimode_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
