#include <deployment.h>
#include <po_hi_types.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Working Copy from ra9b385bc*/
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_bus_id device_lead_accessed_buses[1] = {bus_thebus};
__po_hi_entity_t __po_hi_port_global_to_entity[__PO_HI_NB_PORTS] = {pacemakersw_vrptimeout_k_entity,pacemakersw_vrptimeout_k_entity,pacemakersw_lrltimeout_k_entity,pacemakersw_lrltimeout_k_entity,pacemakersw_vvimode_k_entity,pacemakersw_vvimode_k_entity,pacemakersw_vvimode_k_entity,pacemakersw_vvimode_k_entity,pacemakersw_vvimode_k_entity,pacemakersw_vvimode_k_entity,pacemakersw_vvimode_k_entity};
char* __po_hi_port_global_names[__PO_HI_NB_PORTS] = {"pacemakersw_vvimode_global_p_or_n1","pacemakersw_vvimode_global_vrp_timeout","pacemakersw_vvimode_global_p_or_n2","pacemakersw_vvimode_global_lrl_timeout","pacemakersw_global_s","pacemakersw_lrltimeout_global_output","pacemakersw_vrptimeout_global_output","pacemakersw_global_p","pacemakersw_global_n","pacemakersw_vrptimeout_global_input","pacemakersw_lrltimeout_global_input"};
char* __po_hi_port_global_model_names[__PO_HI_NB_PORTS] = {"input","output","input","output","s","lrl_timeout","vrp_timeout","p","n","p_or_n1","p_or_n2"};
__po_hi_port_kind_t __po_hi_port_global_kind[__PO_HI_NB_PORTS] = {__PO_HI_IN_EVENT_INTRA_PROCESS,__PO_HI_OUT_EVENT_INTRA_PROCESS,__PO_HI_IN_EVENT_INTRA_PROCESS,__PO_HI_OUT_EVENT_INTRA_PROCESS,__PO_HI_IN_EVENT_INTER_PROCESS,__PO_HI_IN_EVENT_INTRA_PROCESS,__PO_HI_IN_EVENT_INTRA_PROCESS,__PO_HI_OUT_EVENT_INTER_PROCESS,__PO_HI_OUT_EVENT_INTER_PROCESS,__PO_HI_OUT_EVENT_INTRA_PROCESS,__PO_HI_OUT_EVENT_INTRA_PROCESS};
__po_hi_uint32_t __po_hi_port_global_data_size[__PO_HI_NB_PORTS] = {};
__po_hi_uint32_t __po_hi_port_global_queue_size[__PO_HI_NB_PORTS] = {1,1,1,1,1,1,1,1,1,1,1};
__po_hi_local_port_t __po_hi_port_global_to_local[__PO_HI_NB_PORTS] = {vrptimeout_local_input,vrptimeout_local_output,lrltimeout_local_input,lrltimeout_local_output,vvimode_local_s,vvimode_local_lrl_timeout,vvimode_local_vrp_timeout,vvimode_local_p,vvimode_local_n,vvimode_local_p_or_n1,vvimode_local_p_or_n2};
__po_hi_node_t __po_hi_entity_table[__PO_HI_NB_ENTITIES] = {pacemakersw_k,pacemakersw_k,pacemakersw_k};
__po_hi_uint8_t __po_hi_deployment_endiannesses[__PO_HI_NB_NODES] = {__PO_HI_LITTLEENDIAN};
char* __po_hi_devices_naming[__PO_HI_NB_DEVICES] = {"noaddr"};
__po_hi_uint32_t* __po_hi_devices_configuration_values[__PO_HI_NB_DEVICES] = {0};
__po_hi_uint32_t __po_hi_devices_nb_accessed_buses[__PO_HI_NB_DEVICES] = {1};
__po_hi_bus_id* __po_hi_devices_accessed_buses[__PO_HI_NB_DEVICES] = {device_lead_accessed_buses};
__po_hi_device_id __po_hi_port_to_device[__PO_HI_NB_PORTS] = {-1,-1,-1,-1,lead_device_id,-1,-1,lead_device_id,lead_device_id,-1,-1};
__po_hi_port_t __po_hi_devices_to_nodes[__PO_HI_NB_DEVICES] = {pacemakersw_k};

