#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
#include <po_hi_types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Working Copy from ra9b385bc*/

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define __PO_HI_MY_NODE pacemakersw_k

#define __PO_HI_MY_NODE_NAME "pacemakersw_k"

#define __po_hi_vrptimeout_nb_ports 2

#define __po_hi_lrltimeout_nb_ports 2

#define __po_hi_vvimode_nb_ports 7

/*  For each node in the distributed application add an enumerator*/

typedef enum
{
  pacemakersw_k = 0
} __po_hi_node_t;

typedef enum
{
  invalid_protocol = -1
} __po_hi_protocol_t;

/*  For each thread in the distributed application nodes, add an enumerator*/

typedef enum
{
  pacemakersw_vrptimeout_k_entity = 0,
  pacemakersw_lrltimeout_k_entity = 1,
  pacemakersw_vvimode_k_entity = 2,
  invalid_entity = -1
} __po_hi_entity_t;

typedef enum
{
  pacemakersw_vrptimeout_k = 0,
  pacemakersw_lrltimeout_k = 1,
  pacemakersw_vvimode_k = 2,
  invalid_task_id = -1
} __po_hi_task_id;

typedef enum
{
  invalid_device_id = -1,
  lead_device_id = 0
} __po_hi_device_id;

typedef enum
{
  invalid_bus_id = -1,
  bus_thebus = 0
} __po_hi_bus_id;

#define __PO_HI_NB_TASKS 3

#define __PO_HI_TASKS_STACK 0

#define __PO_HI_NB_PROTECTED 0

#define __PO_HI_NB_NODES 1

#define __PO_HI_NB_ENTITIES 3

#define __PO_HI_NB_PORTS 11

typedef enum
{
  vrptimeout_global_input = 0,
  vrptimeout_global_output = 1,
  lrltimeout_global_input = 2,
  lrltimeout_global_output = 3,
  vvimode_global_s = 4,
  vvimode_global_lrl_timeout = 5,
  vvimode_global_vrp_timeout = 6,
  vvimode_global_p = 7,
  vvimode_global_n = 8,
  vvimode_global_p_or_n1 = 9,
  vvimode_global_p_or_n2 = 10,
  invalid_port_t = -1,
  constant_out_identifier = 12
} __po_hi_port_t;

typedef enum
{
  vrptimeout_local_input = 0,
  vrptimeout_local_output = 1,
  lrltimeout_local_input = 0,
  lrltimeout_local_output = 1,
  vvimode_local_s = 0,
  vvimode_local_lrl_timeout = 1,
  vvimode_local_vrp_timeout = 2,
  vvimode_local_p = 3,
  vvimode_local_n = 4,
  vvimode_local_p_or_n1 = 5,
  vvimode_local_p_or_n2 = 6,
  invalid_local_port_t = -1
} __po_hi_local_port_t;

#define __PO_HI_NB_DEVICES 1

#define __PO_HI_NB_BUSES 1

#define __PO_HI_NB_PROTOCOLS 0

#define __PO_HI_PORT_TYPE_CONTENT __po_hi_vrptimeout_nb_ports, __po_hi_lrltimeout_nb_ports, __po_hi_vvimode_nb_ports

#endif
