#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Working Copy from ra9b385bc*/
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/

/*!
 * \fn __PO_HI_MAIN_TYPE __PO_HI_MAIN_NAME (void)
 * \brief Main function executed by the system
 *
 * Full function name and return types are available  in the PolyORB-HI-C 
 * runtime header files.
 */
__PO_HI_MAIN_TYPE __PO_HI_MAIN_NAME (void)
{
  
/*!
 * \var period
 * \brief Variable for task period
 *
 * This variable is used to store the valueof the period of a task when we 
 * create it. The value put in the variable is set according to AADL model 
 * description
 */
  __po_hi_time_t period;

  __po_hi_initialize_early ();
  
/*!
 * Initialize the runtime
 */
  __po_hi_initialize ();
  
/*!
 * Store the period time for task vrptimeout
 */
  __po_hi_milliseconds (&(period), 30);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (pacemakersw_vrptimeout_k, &(period), __PO_HI_DEFAULT_PRIORITY, 0, 0, vrptimeout_job);
  
/*!
 * Store the period time for task lrltimeout
 */
  __po_hi_milliseconds (&(period), 100);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (pacemakersw_lrltimeout_k, &(period), __PO_HI_DEFAULT_PRIORITY, 0, 0, lrltimeout_job);
  
/*!
 * Store the period time for task vvimode
 */
  __po_hi_milliseconds (&(period), 30);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (pacemakersw_vvimode_k, &(period), __PO_HI_DEFAULT_PRIORITY, 0, 0, vvimode_job);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Used to switch the main task to sleep all the time
 */
  __po_hi_wait_for_tasks ();
  
/*!
 * Return Statement
 */
  return (__PO_HI_MAIN_RETURN);
}


