#ifndef __OCARINA_GENERATED_REQUEST_H_
#define __OCARINA_GENERATED_REQUEST_H_ 
#include <types.h>
#include <po_hi_types.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Working Copy from ra9b385bc*/

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

/*  Enumeration type for all the operations in the distributed application.*/

typedef struct
{
  __po_hi_port_t port;

  union
  {
    struct
    {
      __po_hi_bool_t vrptimeout_global_input;

    } vrptimeout_global_input;

    struct
    {
      __po_hi_bool_t vrptimeout_global_output;

    } vrptimeout_global_output;

    struct
    {
      __po_hi_bool_t lrltimeout_global_input;

    } lrltimeout_global_input;

    struct
    {
      __po_hi_bool_t lrltimeout_global_output;

    } lrltimeout_global_output;

    struct
    {
      __po_hi_bool_t vvimode_global_s;

    } vvimode_global_s;

    struct
    {
      __po_hi_bool_t vvimode_global_lrl_timeout;

    } vvimode_global_lrl_timeout;

    struct
    {
      __po_hi_bool_t vvimode_global_vrp_timeout;

    } vvimode_global_vrp_timeout;

    struct
    {
      __po_hi_bool_t vvimode_global_p;

    } vvimode_global_p;

    struct
    {
      __po_hi_bool_t vvimode_global_n;

    } vvimode_global_n;

    struct
    {
      __po_hi_bool_t vvimode_global_p_or_n1;

    } vvimode_global_p_or_n1;

    struct
    {
      __po_hi_bool_t vvimode_global_p_or_n2;

    } vvimode_global_p_or_n2;

  } vars;

} __po_hi_request_t;

#define __PO_HI_NB_OPERATIONS 0

#endif
