#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Working Copy from ra9b385bc*/
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"vrptimeout_global_input","vrptimeout_global_output","lrltimeout_global_input","lrltimeout_global_output","vvimode_global_s","vvimode_global_lrl_timeout","vvimode_global_vrp_timeout","vvimode_global_p","vvimode_global_n","vvimode_global_p_or_n1","vvimode_global_p_or_n2"};

