#include "subprograms.h"
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Working Copy from ra9b385bc*/
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void dual_or_timer_job (void);
void pacemaker_pkg__dualortimer_spg_impl (void)
{

  dual_or_timer_job ();
}

void vvi_mode_job (void);
void pacemaker_pkg__vvimode_spg_impl (void)
{

  vvi_mode_job ();
}


