#include <activity.h>
#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <po_hi_task.h>
#include "subprograms.h"
#include <po_hi_transport.h>
#include <po_hi_main.h>
#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Working Copy from ra9b385bc*/
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_main_initialize (void);
__po_hi_port_t __po_hi_vrptimeout_output_local_destinations[1] = {vvimode_global_vrp_timeout};
__po_hi_port_id_t __po_hi_vrptimeout_woffsets[__po_hi_vrptimeout_nb_ports];
__po_hi_port_id_t __po_hi_vrptimeout_offsets[__po_hi_vrptimeout_nb_ports];
__po_hi_port_id_t __po_hi_vrptimeout_used_size[__po_hi_vrptimeout_nb_ports];
__po_hi_port_id_t __po_hi_vrptimeout_empties[__po_hi_vrptimeout_nb_ports];
__po_hi_port_id_t __po_hi_vrptimeout_first[__po_hi_vrptimeout_nb_ports];
__po_hi_request_t __po_hi_vrptimeout_recent[__po_hi_vrptimeout_nb_ports];
__po_hi_request_t __po_hi_vrptimeout_queue[16];
__po_hi_uint16_t __po_hi_vrptimeout_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_vrptimeout_history[16];
__po_hi_port_id_t __po_hi_vrptimeout_n_dest[__po_hi_vrptimeout_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vrptimeout_fifo_size[__po_hi_vrptimeout_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vrptimeout_destinations[__po_hi_vrptimeout_nb_ports] = {NULL,__po_hi_vrptimeout_output_local_destinations};

/*!
 * \fn void vrptimeout_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vrptimeout
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vrptimeout_deliver) stores the incoming request for the taskvrptimeout
 */
void vrptimeout_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vrptimeout_global_input:
    {
      __po_hi_gqueue_store_in (pacemakersw_vrptimeout_k, vrptimeout_local_input, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vrptimeout_job (void)
 * \brief Function executed by the task vrptimeout
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : VRPTimeout*/
/*  Get the IN ports values*/
void* vrptimeout_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (pacemakersw_vrptimeout_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (pacemakersw_vrptimeout_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (pacemakersw_vrptimeout_k, &(port));
    __po_hi_compute_next_period (pacemakersw_vrptimeout_k);
    /*  Call implementation*/
    pacemaker_pkg__dualortimer_spg_impl ();
    /*  Set the OUT port values*/
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (pacemakersw_vrptimeout_k, vrptimeout_global_output);
    (void)error;
    __po_hi_wait_for_next_period (pacemakersw_vrptimeout_k);
  }
}

__po_hi_port_t __po_hi_lrltimeout_output_local_destinations[1] = {vvimode_global_lrl_timeout};
__po_hi_port_id_t __po_hi_lrltimeout_woffsets[__po_hi_lrltimeout_nb_ports];
__po_hi_port_id_t __po_hi_lrltimeout_offsets[__po_hi_lrltimeout_nb_ports];
__po_hi_port_id_t __po_hi_lrltimeout_used_size[__po_hi_lrltimeout_nb_ports];
__po_hi_port_id_t __po_hi_lrltimeout_empties[__po_hi_lrltimeout_nb_ports];
__po_hi_port_id_t __po_hi_lrltimeout_first[__po_hi_lrltimeout_nb_ports];
__po_hi_request_t __po_hi_lrltimeout_recent[__po_hi_lrltimeout_nb_ports];
__po_hi_request_t __po_hi_lrltimeout_queue[16];
__po_hi_uint16_t __po_hi_lrltimeout_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_lrltimeout_history[16];
__po_hi_port_id_t __po_hi_lrltimeout_n_dest[__po_hi_lrltimeout_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_lrltimeout_fifo_size[__po_hi_lrltimeout_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_lrltimeout_destinations[__po_hi_lrltimeout_nb_ports] = {NULL,__po_hi_lrltimeout_output_local_destinations};

/*!
 * \fn void lrltimeout_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task lrltimeout
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (lrltimeout_deliver) stores the incoming request for the tasklrltimeout
 */
void lrltimeout_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case lrltimeout_global_input:
    {
      __po_hi_gqueue_store_in (pacemakersw_lrltimeout_k, lrltimeout_local_input, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* lrltimeout_job (void)
 * \brief Function executed by the task lrltimeout
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : LRLTimeout*/
/*  Get the IN ports values*/
void* lrltimeout_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (pacemakersw_lrltimeout_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (pacemakersw_lrltimeout_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (pacemakersw_lrltimeout_k, &(port));
    __po_hi_compute_next_period (pacemakersw_lrltimeout_k);
    /*  Call implementation*/
    pacemaker_pkg__dualortimer_spg_impl ();
    /*  Set the OUT port values*/
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (pacemakersw_lrltimeout_k, lrltimeout_global_output);
    (void)error;
    __po_hi_wait_for_next_period (pacemakersw_lrltimeout_k);
  }
}

__po_hi_port_t __po_hi_vvimode_p_local_destinations[1] = {lead_global_ventriclepulse};
__po_hi_port_t __po_hi_vvimode_n_local_destinations[1] = {lead_global_normal_beat};
__po_hi_port_t __po_hi_vvimode_p_or_n1_local_destinations[1] = {vrptimeout_global_input};
__po_hi_port_t __po_hi_vvimode_p_or_n2_local_destinations[1] = {lrltimeout_global_input};
__po_hi_port_id_t __po_hi_vvimode_woffsets[__po_hi_vvimode_nb_ports];
__po_hi_port_id_t __po_hi_vvimode_offsets[__po_hi_vvimode_nb_ports];
__po_hi_port_id_t __po_hi_vvimode_used_size[__po_hi_vvimode_nb_ports];
__po_hi_port_id_t __po_hi_vvimode_empties[__po_hi_vvimode_nb_ports];
__po_hi_port_id_t __po_hi_vvimode_first[__po_hi_vvimode_nb_ports];
__po_hi_request_t __po_hi_vvimode_recent[__po_hi_vvimode_nb_ports];
__po_hi_request_t __po_hi_vvimode_queue[48];
__po_hi_uint16_t __po_hi_vvimode_total_fifo_size = 48;
__po_hi_local_port_t __po_hi_vvimode_history[48];
__po_hi_port_id_t __po_hi_vvimode_n_dest[__po_hi_vvimode_nb_ports] = {0,0,0,1,1,1,1};
__po_hi_port_id_t __po_hi_vvimode_fifo_size[__po_hi_vvimode_nb_ports] = {16,16,16,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vvimode_destinations[__po_hi_vvimode_nb_ports] = {NULL,NULL,NULL,__po_hi_vvimode_p_local_destinations,__po_hi_vvimode_n_local_destinations,__po_hi_vvimode_p_or_n1_local_destinations,__po_hi_vvimode_p_or_n2_local_destinations};

/*!
 * \fn void vvimode_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vvimode
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vvimode_deliver) stores the incoming request for the taskvvimode
 */
void vvimode_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vvimode_global_s:
    {
      __po_hi_gqueue_store_in (pacemakersw_vvimode_k, vvimode_local_s, request);

      break;
    }
    case vvimode_global_lrl_timeout:
    {
      __po_hi_gqueue_store_in (pacemakersw_vvimode_k, vvimode_local_lrl_timeout, request);

      break;
    }
    case vvimode_global_vrp_timeout:
    {
      __po_hi_gqueue_store_in (pacemakersw_vvimode_k, vvimode_local_vrp_timeout, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vvimode_job (void)
 * \brief Function executed by the task vvimode
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : VVIMode*/
/*  Get the IN ports values*/
void* vvimode_job (void)
{
  pacemaker_pkg__int_impl vrp;
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (pacemakersw_vvimode_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (pacemakersw_vvimode_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (pacemakersw_vvimode_k, &(port));
    __po_hi_compute_next_period (pacemakersw_vvimode_k);
    /*  Call implementation*/
    pacemaker_pkg__vvimode_spg_impl ();
    /*  Set the OUT port values*/
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (pacemakersw_vvimode_k, vvimode_global_p);
    (void)error;
    error =
     __po_hi_send_output (pacemakersw_vvimode_k, vvimode_global_n);
    (void)error;
    error =
     __po_hi_send_output (pacemakersw_vvimode_k, vvimode_global_p_or_n1);
    (void)error;
    error =
     __po_hi_send_output (pacemakersw_vvimode_k, vvimode_global_p_or_n2);
    (void)error;
    __po_hi_wait_for_next_period (pacemakersw_vvimode_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case pacemakersw_vrptimeout_k_entity:
    {
      vrptimeout_deliver (request);

      break;
    }
    case pacemakersw_lrltimeout_k_entity:
    {
      lrltimeout_deliver (request);

      break;
    }
    case pacemakersw_vvimode_k_entity:
    {
      vvimode_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_main_initialize (void)
{

  __po_hi_gqueue_init (pacemakersw_vrptimeout_k, __po_hi_vrptimeout_nb_ports, __po_hi_vrptimeout_queue, __po_hi_vrptimeout_fifo_size, __po_hi_vrptimeout_first, __po_hi_vrptimeout_offsets, __po_hi_vrptimeout_woffsets, __po_hi_vrptimeout_n_dest, __po_hi_vrptimeout_destinations, __po_hi_vrptimeout_used_size, __po_hi_vrptimeout_history, __po_hi_vrptimeout_recent, __po_hi_vrptimeout_empties, __po_hi_vrptimeout_total_fifo_size);
  __po_hi_gqueue_init (pacemakersw_lrltimeout_k, __po_hi_lrltimeout_nb_ports, __po_hi_lrltimeout_queue, __po_hi_lrltimeout_fifo_size, __po_hi_lrltimeout_first, __po_hi_lrltimeout_offsets, __po_hi_lrltimeout_woffsets, __po_hi_lrltimeout_n_dest, __po_hi_lrltimeout_destinations, __po_hi_lrltimeout_used_size, __po_hi_lrltimeout_history, __po_hi_lrltimeout_recent, __po_hi_lrltimeout_empties, __po_hi_lrltimeout_total_fifo_size);
  __po_hi_gqueue_init (pacemakersw_vvimode_k, __po_hi_vvimode_nb_ports, __po_hi_vvimode_queue, __po_hi_vvimode_fifo_size, __po_hi_vvimode_first, __po_hi_vvimode_offsets, __po_hi_vvimode_woffsets, __po_hi_vvimode_n_dest, __po_hi_vvimode_destinations, __po_hi_vvimode_used_size, __po_hi_vvimode_history, __po_hi_vvimode_recent, __po_hi_vvimode_empties, __po_hi_vvimode_total_fifo_size);
}


