#ifndef __OCARINA_GENERATED_SUBPROGRAMS_H_
#define __OCARINA_GENERATED_SUBPROGRAMS_H_ 
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Working Copy from ra9b385bc*/

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void pacemaker_pkg__dualortimer_spg_impl (void);

void pacemaker_pkg__vvimode_spg_impl (void);

#endif
